application: restapi1
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

# Endpoints handler
- url: /_ah/spi/.*
  script: api.application

- url: /.*
  script: main.app
  

libraries:
- name: webapp2
  version: "2.5.2"
  
# Needed for endpoints/users_id_token.py.
- name: pycrypto
  version: "2.6"
